import type { Metadata } from 'next'
import './globals.css'
import { inter } from '@/app/ui/fonts';
import { titilium } from '@/app/ui/fonts';
import Navbar from './ui/navbar';

export const metadata: Metadata = {
  title: 'Mercado No Lineal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${titilium.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
